### ISSUE TITLE
No visual feedback when shortcut is correct - Image is no longer found 

### ISSUE THREAD

**Issue by leifhanack** [leifhanack/intellijidea-shortcut-trainer#2]
```
  Calling `ClassLoader#getResource` with leading slash doesn't work; strip
  
  com.intellij.diagnostic.PluginException: /images/correct.png [Plugin: Shortcut Trainer]
at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.kt:610)
at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1408)
at de.strug.shortcut_trainer.ShortcutTrainerDialog.handleKeyEventAsShortcut(ShortcutTrainerDialog.java:45)

```

**Comment by leifhanack** [comment]
I updated the plugin and added textual feedback
